location = /api/lp/v1/history.json {
    try_files $uri =404;
    default_type application/json;
    expires 5m;
    limit_except GET {
        deny all;
    }
}

location /api/lp/ {
    return 404;
}
